name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Build with PyInstaller
        env:
          APP_VERSION: ${{ github.ref_name }}
        run: |
          python -m pyinstaller --clean pixbox.spec --name "pixbox-$env:APP_VERSION"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pixbox-release
          path: dist/
